substitutions:
  _REGION: us-east1
  _REPOSITORY: credentialing
  _SERVICE: credentialing-drive

steps:
  - name: gcr.io/cloud-builders/docker
    dir: credentialing-drive
    args:
      - build
      - --tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID
      - .
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID
